/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Evento } from "./Evento";
import { EventoCountArgs } from "./EventoCountArgs";
import { EventoFindManyArgs } from "./EventoFindManyArgs";
import { EventoFindUniqueArgs } from "./EventoFindUniqueArgs";
import { CreateEventoArgs } from "./CreateEventoArgs";
import { UpdateEventoArgs } from "./UpdateEventoArgs";
import { DeleteEventoArgs } from "./DeleteEventoArgs";
import { Listing } from "../../listing/base/Listing";
import { User } from "../../user/base/User";
import { EventoService } from "../evento.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Evento)
export class EventoResolverBase {
  constructor(
    protected readonly service: EventoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Evento",
    action: "read",
    possession: "any",
  })
  async _eventosMeta(
    @graphql.Args() args: EventoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Evento])
  @nestAccessControl.UseRoles({
    resource: "Evento",
    action: "read",
    possession: "any",
  })
  async eventos(@graphql.Args() args: EventoFindManyArgs): Promise<Evento[]> {
    return this.service.eventos(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Evento, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Evento",
    action: "read",
    possession: "own",
  })
  async evento(
    @graphql.Args() args: EventoFindUniqueArgs
  ): Promise<Evento | null> {
    const result = await this.service.evento(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Evento)
  @nestAccessControl.UseRoles({
    resource: "Evento",
    action: "create",
    possession: "any",
  })
  async createEvento(@graphql.Args() args: CreateEventoArgs): Promise<Evento> {
    return await this.service.createEvento({
      ...args,
      data: {
        ...args.data,

        listing: {
          connect: args.data.listing,
        },

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Evento)
  @nestAccessControl.UseRoles({
    resource: "Evento",
    action: "update",
    possession: "any",
  })
  async updateEvento(
    @graphql.Args() args: UpdateEventoArgs
  ): Promise<Evento | null> {
    try {
      return await this.service.updateEvento({
        ...args,
        data: {
          ...args.data,

          listing: {
            connect: args.data.listing,
          },

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Evento)
  @nestAccessControl.UseRoles({
    resource: "Evento",
    action: "delete",
    possession: "any",
  })
  async deleteEvento(
    @graphql.Args() args: DeleteEventoArgs
  ): Promise<Evento | null> {
    try {
      return await this.service.deleteEvento(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Listing, {
    nullable: true,
    name: "listing",
  })
  @nestAccessControl.UseRoles({
    resource: "Listing",
    action: "read",
    possession: "any",
  })
  async getListing(@graphql.Parent() parent: Evento): Promise<Listing | null> {
    const result = await this.service.getListing(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Evento): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
